---
dist: trusty
language: python
python: "3.5"

# safelist
branches:
  only:
  - master
  - ansible-3

env:
  - CHOOSE_END=stage
  - CHOOSE_END=prod  
  
before_install:
  - sudo apt-get -y update
  
install:
  - wget https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip
  - sudo unzip -o packer_1.1.3_linux_amd64.zip -d /usr/local/bin
  - wget https://releases.hashicorp.com/terraform/0.11.2/terraform_0.11.2_linux_amd64.zip
  - sudo unzip -o terraform_0.11.2_linux_amd64.zip -d /usr/local/bin
  - wget https://github.com/wata727/tflint/releases/download/v0.5.4/tflint_linux_amd64.zip
  - sudo unzip -o tflint_linux_amd64.zip -d /usr/local/bin
  - pip install ansible
  - pip install ansible-lint
  - touch ~/.ssh/appuser.pub && touch ~/.ssh/appuser
  
script:
  - packer validate -var-file=packer/variables.json.example packer/db.json
  - packer validate -var-file=packer/variables.json.example packer/app.json
  - ansible-lint ./ansible/playbooks/site.yml
  - cd terraform/${CHOOSE_END}
  - terraform init
  - terraform validate --var-file=terraform.tfvars.example
  - tflint --var-file=terraform.tfvars.example --error-with-issues
